import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import ShopContextProvider from "@/context/ShopContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Today_Pearl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (

    <html lang="zh-TW">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />

        <ShopContextProvider>

          {children}

        </ShopContextProvider>
        
      </body>
    </html>
  );
}
